"""baseline schema

Revision ID: 7298bca17ff7
Revises: 
Create Date: 2026-07-09 19:24:21.481500

"""
from alembic import op
import sqlalchemy as sa
import utils.database


# revision identifiers, used by Alembic.
revision = '7298bca17ff7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cache_key', sa.String(length=255), nullable=False),
    sa.Column('cache_data', utils.database.DatabaseCompatJSON(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('api_cache', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_api_cache_cache_key'), ['cache_key'], unique=True)
        batch_op.create_index(batch_op.f('ix_api_cache_expires_at'), ['expires_at'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=True),
    sa.Column('last_name', sa.String(length=50), nullable=True),
    sa.Column('home_zip_code', sa.String(length=10), nullable=True),
    sa.Column('max_travel_minutes', sa.Integer(), nullable=True),
    sa.Column('accessibility_needs', sa.Text(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('venue_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('icon_class', sa.String(length=50), nullable=True),
    sa.Column('search_keywords', utils.database.DatabaseCompatArray(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('search_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('search_zip', sa.String(length=10), nullable=True),
    sa.Column('search_radius', sa.Integer(), nullable=True),
    sa.Column('category_filter', sa.Integer(), nullable=True),
    sa.Column('results_count', sa.Integer(), nullable=True),
    sa.Column('accessibility_filter', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['category_filter'], ['venue_categories.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('venues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('google_place_id', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=50), nullable=True),
    sa.Column('zip_code', sa.String(length=10), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('website', sa.String(length=500), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=10, scale=8), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=11, scale=8), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('google_rating', sa.Numeric(precision=2, scale=1), nullable=True),
    sa.Column('price_level', sa.Integer(), nullable=True),
    sa.Column('wheelchair_accessible', sa.Boolean(), nullable=True),
    sa.Column('accessible_parking', sa.Boolean(), nullable=True),
    sa.Column('accessible_restroom', sa.Boolean(), nullable=True),
    sa.Column('elevator_access', sa.Boolean(), nullable=True),
    sa.Column('wide_doorways', sa.Boolean(), nullable=True),
    sa.Column('ramp_access', sa.Boolean(), nullable=True),
    sa.Column('accessible_seating', sa.Boolean(), nullable=True),
    sa.Column('accessibility_notes', sa.Text(), nullable=True),
    sa.Column('hours_monday', sa.String(length=50), nullable=True),
    sa.Column('hours_tuesday', sa.String(length=50), nullable=True),
    sa.Column('hours_wednesday', sa.String(length=50), nullable=True),
    sa.Column('hours_thursday', sa.String(length=50), nullable=True),
    sa.Column('hours_friday', sa.String(length=50), nullable=True),
    sa.Column('hours_saturday', sa.String(length=50), nullable=True),
    sa.Column('hours_sunday', sa.String(length=50), nullable=True),
    sa.Column('seasonal_hours', sa.Text(), nullable=True),
    sa.Column('experience_tags', utils.database.DatabaseCompatArray(), nullable=True),
    sa.Column('interestingness_score', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('event_frequency_score', sa.Integer(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('verified_accessible', sa.Boolean(), nullable=True),
    sa.Column('photo_urls', utils.database.DatabaseCompatArray(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['venue_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('venues', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_venues_google_place_id'), ['google_place_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_venues_latitude'), ['latitude'], unique=False)
        batch_op.create_index(batch_op.f('ix_venues_longitude'), ['longitude'], unique=False)
        batch_op.create_index(batch_op.f('ix_venues_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_venues_wheelchair_accessible'), ['wheelchair_accessible'], unique=False)

    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('venue_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('end_time', sa.Time(), nullable=True),
    sa.Column('duration_hours', sa.Float(), nullable=True),
    sa.Column('is_fun', sa.Boolean(), nullable=True),
    sa.Column('is_interesting', sa.Boolean(), nullable=True),
    sa.Column('is_off_beat', sa.Boolean(), nullable=True),
    sa.Column('cost', sa.String(length=100), nullable=True),
    sa.Column('registration_required', sa.Boolean(), nullable=True),
    sa.Column('registration_url', sa.String(length=500), nullable=True),
    sa.Column('contact_phone', sa.String(length=20), nullable=True),
    sa.Column('contact_email', sa.String(length=120), nullable=True),
    sa.Column('max_participants', sa.Integer(), nullable=True),
    sa.Column('age_restriction', sa.String(length=50), nullable=True),
    sa.Column('audience_type', sa.String(length=100), nullable=True),
    sa.Column('wheelchair_accessible', sa.Boolean(), nullable=True),
    sa.Column('hearing_accessible', sa.Boolean(), nullable=True),
    sa.Column('vision_accessible', sa.Boolean(), nullable=True),
    sa.Column('mobility_accommodations', sa.Text(), nullable=True),
    sa.Column('accessibility_notes', sa.Text(), nullable=True),
    sa.Column('indoor_outdoor', sa.String(length=20), nullable=True),
    sa.Column('weather_dependent', sa.Boolean(), nullable=True),
    sa.Column('bring_items', sa.Text(), nullable=True),
    sa.Column('provided_items', sa.Text(), nullable=True),
    sa.Column('experience_tags', utils.database.DatabaseCompatArray(), nullable=True),
    sa.Column('fun_score', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('learning_potential', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('uniqueness_score', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('event_url', sa.String(length=500), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('social_media_links', utils.database.DatabaseCompatArray(), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('source_api', sa.String(length=50), nullable=True),
    sa.Column('external_event_id', sa.String(length=100), nullable=True),
    sa.Column('last_verified', sa.DateTime(), nullable=True),
    sa.Column('verification_status', sa.String(length=20), nullable=True),
    sa.Column('api_data', sa.JSON(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_recurring', sa.Boolean(), nullable=True),
    sa.Column('recurrence_pattern', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_events_is_fun'), ['is_fun'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_is_interesting'), ['is_interesting'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_is_off_beat'), ['is_off_beat'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_start_date'), ['start_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_title'), ['title'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_wheelchair_accessible'), ['wheelchair_accessible'], unique=False)

    op.create_table('user_favorites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('venue_id', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('personal_accessibility_rating', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'venue_id', name='unique_user_venue_favorite')
    )
    op.create_table('user_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('venue_id', sa.Integer(), nullable=False),
    sa.Column('visit_date', sa.Date(), nullable=True),
    sa.Column('overall_rating', sa.Integer(), nullable=True),
    sa.Column('accessibility_rating', sa.Integer(), nullable=True),
    sa.Column('review_text', sa.Text(), nullable=True),
    sa.Column('accessibility_notes', sa.Text(), nullable=True),
    sa.Column('would_return', sa.Boolean(), nullable=True),
    sa.Column('recommended_for_wheelchair', sa.Boolean(), nullable=True),
    sa.Column('photos', utils.database.DatabaseCompatArray(), nullable=True),
    sa.Column('weather_conditions', sa.String(length=100), nullable=True),
    sa.Column('visit_duration_hours', sa.Numeric(precision=3, scale=1), nullable=True),
    sa.Column('companion_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('event_favorites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('reminder_set', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'event_id')
    )
    op.create_table('event_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('attended', sa.Boolean(), nullable=True),
    sa.Column('overall_rating', sa.Integer(), nullable=True),
    sa.Column('accessibility_rating', sa.Integer(), nullable=True),
    sa.Column('fun_rating', sa.Integer(), nullable=True),
    sa.Column('review_text', sa.Text(), nullable=True),
    sa.Column('accessibility_notes', sa.Text(), nullable=True),
    sa.Column('would_attend_again', sa.Boolean(), nullable=True),
    sa.Column('would_recommend', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('event_reviews')
    op.drop_table('event_favorites')
    op.drop_table('user_reviews')
    op.drop_table('user_favorites')
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_events_wheelchair_accessible'))
        batch_op.drop_index(batch_op.f('ix_events_title'))
        batch_op.drop_index(batch_op.f('ix_events_start_date'))
        batch_op.drop_index(batch_op.f('ix_events_is_off_beat'))
        batch_op.drop_index(batch_op.f('ix_events_is_interesting'))
        batch_op.drop_index(batch_op.f('ix_events_is_fun'))

    op.drop_table('events')
    with op.batch_alter_table('venues', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_venues_wheelchair_accessible'))
        batch_op.drop_index(batch_op.f('ix_venues_name'))
        batch_op.drop_index(batch_op.f('ix_venues_longitude'))
        batch_op.drop_index(batch_op.f('ix_venues_latitude'))
        batch_op.drop_index(batch_op.f('ix_venues_google_place_id'))

    op.drop_table('venues')
    op.drop_table('search_history')
    op.drop_table('venue_categories')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('api_cache', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_api_cache_expires_at'))
        batch_op.drop_index(batch_op.f('ix_api_cache_cache_key'))

    op.drop_table('api_cache')
    # ### end Alembic commands ###
